# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoldenTicket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoldenTicket
  pod 'Hero'
  pod 'SideMenu'
  pod 'TextFieldEffects'
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 4.10.1'
end
